package mib;
import oru.inf.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author Lukas Brolin, Daniel Antonsson & Jonatan Angergård
 */
public class AdminUtrustning extends javax.swing.JFrame {

    /**
     * Creates new form AdminUtrustning
     */
    public AdminUtrustning() {
        initComponents();
    }
    

    public void setAgentNamn(String agent)
    {
        lblAgentNamn.setText(agent);
    }
    
    private void clearBoxes()
    {
        txtAdminUtrustningsBenamning.setText("");
        txtAdminUtrustningsID.setText("");
        txtSokUtrustning.setText("");
        txtTilldelaUtrustningsID.setText("");
        txtTilldelaAgentID.setText("");
    }
    
    private void listaUtrustning()
    {
        try
        {
            
            String fraga= "SELECT BENAMNING, UTRUSTNINGS_ID FROM UTRUSTNING";
            ArrayList<HashMap<String,String>> lista = (DataBaseConnection.getDB().fetchRows(fraga));
            DefaultListModel<String> model = new DefaultListModel<>();
            lstAdminUtrustning.setModel(model);
            
            for(HashMap<String, String> map: lista)
            {
                int i = 0;
                for(String key : map.keySet())
                {
                    model.addElement(map.get(key));
                    if(i==1)
                    {
                        String agentFraga = "SELECT NAMN FROM AGENT JOIN INNEHAR_UTRUSTNING ON AGENT.AGENT_ID = INNEHAR_UTRUSTNING.AGENT_ID WHERE INNEHAR_UTRUSTNING.UTRUSTNINGS_ID = " + map.get(key);
                        String agentSvar = DataBaseConnection.getDB().fetchSingle(agentFraga);
                        if(agentSvar == null)
                        {
                            model.addElement("Ej utkvitterad");
                        }
                        else
                        {
                            model.addElement("Utkvitterad av: " + DataBaseConnection.getDB().fetchSingle(agentFraga));
                        }
                        
                    }
                    i++;
                }
                String newRow = "-------------------------------------------------";
                model.addElement(newRow);
                clearBoxes();
            }
            
        }
        catch(InfException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void listaMinUtrustning()
    {
        try
        {
            String fraga= "SELECT UTRUSTNING.UTRUSTNINGS_ID, UTRUSTNING.BENAMNING FROM UTRUSTNING INNER JOIN INNEHAR_UTRUSTNING ON UTRUSTNING.UTRUSTNINGS_ID = INNEHAR_UTRUSTNING.UTRUSTNINGS_ID WHERE AGENT_ID = " + Inloggad.getIDInloggad() + "";
            ArrayList<HashMap<String,String>> lista = (DataBaseConnection.getDB().fetchRows(fraga));
            DefaultListModel<String> model = new DefaultListModel<>();
            lstAdminMinUtrustning.setModel(model);
            
            for(HashMap<String, String> map: lista)
            {
                for(String key : map.keySet())
                {
                    model.addElement(map.get(key));
                }
                String newRow = "-------------------------------------------------";
                model.addElement(newRow);
                clearBoxes();
            }
            
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFonster = new javax.swing.JPanel();
        pnlBorderTop = new javax.swing.JPanel();
        lblRubrik = new javax.swing.JLabel();
        lblAgentIkon = new javax.swing.JLabel();
        lblAgentNamn = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        pnlBorderBottom = new javax.swing.JPanel();
        lblValjUtrustning = new javax.swing.JLabel();
        btnSok = new javax.swing.JButton();
        lblUtrustningsID = new javax.swing.JLabel();
        lblBenamning = new javax.swing.JLabel();
        txtAdminUtrustningsID = new javax.swing.JTextField();
        txtAdminUtrustningsBenamning = new javax.swing.JTextField();
        txtSokUtrustning = new javax.swing.JTextField();
        btnRegistreraUtrustning = new javax.swing.JButton();
        scpLista = new javax.swing.JScrollPane();
        lstAdminUtrustning = new javax.swing.JList<>();
        btnRaderaUtrustning = new javax.swing.JButton();
        lblInstruktioner = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnListaAlla1 = new javax.swing.JButton();
        btnTilldelaUtrustning = new javax.swing.JButton();
        lblBenamning1 = new javax.swing.JLabel();
        lblUtrustningsID1 = new javax.swing.JLabel();
        txtTilldelaUtrustningsID = new javax.swing.JTextField();
        txtTilldelaAgentID = new javax.swing.JTextField();
        lblInstruktioner1 = new javax.swing.JLabel();
        scpMinUtrustning = new javax.swing.JScrollPane();
        lstAdminMinUtrustning = new javax.swing.JList<>();
        jSeparator5 = new javax.swing.JSeparator();
        btnAterlamnaUtrustning = new javax.swing.JButton();
        btnUtkvitteraUtrustning = new javax.swing.JButton();
        btnListaMinUtrustning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        pnlFonster.setBackground(new java.awt.Color(255, 255, 255));
        pnlFonster.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlFonster.setMinimumSize(new java.awt.Dimension(1000, 600));

        pnlBorderTop.setBackground(new java.awt.Color(220, 220, 220));
        pnlBorderTop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlBorderTop.setMaximumSize(new java.awt.Dimension(1000, 80));
        pnlBorderTop.setMinimumSize(new java.awt.Dimension(1000, 80));

        lblRubrik.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblRubrik.setText("Utrustning");

        lblAgentIkon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/spy.png"))); // NOI18N

        lblAgentNamn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblAgentNamn.setText("Agent K");

        lblAdmin.setFont(new java.awt.Font("Open Sans", 3, 10)); // NOI18N
        lblAdmin.setText("Admin");

        btnHome.setBackground(new java.awt.Color(220, 220, 220));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBorderTopLayout = new javax.swing.GroupLayout(pnlBorderTop);
        pnlBorderTop.setLayout(pnlBorderTopLayout);
        pnlBorderTopLayout.setHorizontalGroup(
            pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRubrik)
                .addGap(309, 309, 309)
                .addComponent(lblAgentIkon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgentNamn)
                    .addComponent(lblAdmin))
                .addGap(15, 15, 15))
        );
        pnlBorderTopLayout.setVerticalGroup(
            pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderTopLayout.createSequentialGroup()
                .addGroup(pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlBorderTopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAgentNamn)
                        .addGap(0, 0, 0)
                        .addComponent(lblAdmin))
                    .addGroup(pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlBorderTopLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(lblRubrik))
                        .addGroup(pnlBorderTopLayout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addGroup(pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAgentIkon)))))
                .addGap(7, 7, 7))
        );

        pnlBorderBottom.setBackground(new java.awt.Color(220, 220, 220));
        pnlBorderBottom.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlBorderBottom.setMaximumSize(new java.awt.Dimension(1000, 40));
        pnlBorderBottom.setMinimumSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout pnlBorderBottomLayout = new javax.swing.GroupLayout(pnlBorderBottom);
        pnlBorderBottom.setLayout(pnlBorderBottomLayout);
        pnlBorderBottomLayout.setHorizontalGroup(
            pnlBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlBorderBottomLayout.setVerticalGroup(
            pnlBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        lblValjUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        lblValjUtrustning.setText("Sök Utrustning:");

        btnSok.setBackground(new java.awt.Color(255, 255, 255));
        btnSok.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        btnSok.setText("Sök");
        btnSok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSok.setContentAreaFilled(false);
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        lblUtrustningsID.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblUtrustningsID.setText("Utrustnings ID:");

        lblBenamning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblBenamning.setText("Benämning:");

        txtAdminUtrustningsID.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtAdminUtrustningsID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAdminUtrustningsBenamning.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtAdminUtrustningsBenamning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSokUtrustning.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtSokUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRegistreraUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistreraUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnRegistreraUtrustning.setText("Registrera ny utrustning");
        btnRegistreraUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegistreraUtrustning.setContentAreaFilled(false);
        btnRegistreraUtrustning.setMaximumSize(new java.awt.Dimension(75, 30));
        btnRegistreraUtrustning.setMinimumSize(new java.awt.Dimension(75, 30));
        btnRegistreraUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraUtrustningActionPerformed(evt);
            }
        });

        scpLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lstAdminUtrustning.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAdminUtrustningValueChanged(evt);
            }
        });
        scpLista.setViewportView(lstAdminUtrustning);

        btnRaderaUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        btnRaderaUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnRaderaUtrustning.setText("Radera utrustning");
        btnRaderaUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRaderaUtrustning.setContentAreaFilled(false);
        btnRaderaUtrustning.setMaximumSize(new java.awt.Dimension(75, 30));
        btnRaderaUtrustning.setMinimumSize(new java.awt.Dimension(75, 30));
        btnRaderaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaUtrustningActionPerformed(evt);
            }
        });

        lblInstruktioner.setFont(new java.awt.Font("Open Sans Semibold", 2, 12)); // NOI18N
        lblInstruktioner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruktioner.setText("Registrera utrustning");
        lblInstruktioner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(1, 10));

        btnListaAlla1.setBackground(new java.awt.Color(255, 255, 255));
        btnListaAlla1.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnListaAlla1.setText("Lista all utrustning");
        btnListaAlla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnListaAlla1.setContentAreaFilled(false);
        btnListaAlla1.setMaximumSize(new java.awt.Dimension(75, 30));
        btnListaAlla1.setMinimumSize(new java.awt.Dimension(75, 30));
        btnListaAlla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaAlla1ActionPerformed(evt);
            }
        });

        btnTilldelaUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        btnTilldelaUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnTilldelaUtrustning.setText("Tilldela utrustning");
        btnTilldelaUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnTilldelaUtrustning.setContentAreaFilled(false);
        btnTilldelaUtrustning.setMaximumSize(new java.awt.Dimension(75, 30));
        btnTilldelaUtrustning.setMinimumSize(new java.awt.Dimension(75, 30));
        btnTilldelaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTilldelaUtrustningActionPerformed(evt);
            }
        });

        lblBenamning1.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblBenamning1.setText("Agent ID:");

        lblUtrustningsID1.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblUtrustningsID1.setText("Utrustnings ID:");

        txtTilldelaUtrustningsID.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtTilldelaUtrustningsID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTilldelaAgentID.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtTilldelaAgentID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblInstruktioner1.setFont(new java.awt.Font("Open Sans Semibold", 2, 12)); // NOI18N
        lblInstruktioner1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruktioner1.setText("Tilldela utrustning");
        lblInstruktioner1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        scpMinUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        scpMinUtrustning.setViewportView(lstAdminMinUtrustning);

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        btnAterlamnaUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        btnAterlamnaUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnAterlamnaUtrustning.setText("Återlämna utrustning");
        btnAterlamnaUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAterlamnaUtrustning.setContentAreaFilled(false);
        btnAterlamnaUtrustning.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAterlamnaUtrustning.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAterlamnaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAterlamnaUtrustningActionPerformed(evt);
            }
        });

        btnUtkvitteraUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        btnUtkvitteraUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnUtkvitteraUtrustning.setText("Utkvittera utrustning");
        btnUtkvitteraUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUtkvitteraUtrustning.setContentAreaFilled(false);
        btnUtkvitteraUtrustning.setMaximumSize(new java.awt.Dimension(75, 30));
        btnUtkvitteraUtrustning.setMinimumSize(new java.awt.Dimension(75, 30));
        btnUtkvitteraUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtkvitteraUtrustningActionPerformed(evt);
            }
        });

        btnListaMinUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        btnListaMinUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnListaMinUtrustning.setText("Lista min utrustning");
        btnListaMinUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnListaMinUtrustning.setContentAreaFilled(false);
        btnListaMinUtrustning.setMaximumSize(new java.awt.Dimension(75, 30));
        btnListaMinUtrustning.setMinimumSize(new java.awt.Dimension(75, 30));
        btnListaMinUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaMinUtrustningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFonsterLayout = new javax.swing.GroupLayout(pnlFonster);
        pnlFonster.setLayout(pnlFonsterLayout);
        pnlFonsterLayout.setHorizontalGroup(
            pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFonsterLayout.createSequentialGroup()
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBorderTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFonsterLayout.createSequentialGroup()
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUtrustningsID)
                                    .addComponent(lblBenamning))
                                .addGap(41, 41, 41)
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAdminUtrustningsID)
                                    .addComponent(txtAdminUtrustningsBenamning)
                                    .addComponent(lblInstruktioner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegistreraUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFonsterLayout.createSequentialGroup()
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUtrustningsID1)
                                    .addComponent(lblBenamning1))
                                .addGap(41, 41, 41)
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTilldelaUtrustningsID)
                                    .addComponent(txtTilldelaAgentID)
                                    .addComponent(lblInstruktioner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTilldelaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scpLista, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListaAlla1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRaderaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUtkvitteraUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scpMinUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAterlamnaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListaMinUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFonsterLayout.createSequentialGroup()
                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                .addComponent(lblValjUtrustning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSokUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))
                        .addComponent(btnSok, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        pnlFonsterLayout.setVerticalGroup(
            pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFonsterLayout.createSequentialGroup()
                .addComponent(pnlBorderTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFonsterLayout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFonsterLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInstruktioner))
                                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblValjUtrustning)
                                            .addComponent(txtSokUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSok))
                                        .addGap(0, 0, 0)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAdminUtrustningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUtrustningsID))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAdminUtrustningsBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBenamning))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRegistreraUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblInstruktioner1)
                                        .addGap(10, 10, 10)
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTilldelaUtrustningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUtrustningsID1))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTilldelaAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBenamning1))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTilldelaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(scpMinUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                            .addComponent(scpLista))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnAterlamnaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnListaAlla1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                                .addComponent(btnUtkvitteraUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(btnRaderaUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnListaMinUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(49, 49, 49))
                    .addGroup(pnlFonsterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFonster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFonster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
    if(Validation.isNotEmpty(txtSokUtrustning))
        {
        try
        {
            String sokOrd = txtSokUtrustning.getText().toLowerCase();
            String fraga = "Select Utrustnings_id, benamning from utrustning";
            ArrayList<HashMap<String, String>> lista = (DataBaseConnection.getDB().fetchRows(fraga));
            DefaultListModel<String> model = new DefaultListModel<>();
            lstAdminUtrustning.setModel(model);
            for(HashMap<String, String> map: lista)
            {
                Boolean skrivitsUt = false;
                for(String key : map.keySet())
                {
                    
                    String utrustning = map.get(key).toLowerCase();
                    /*if(!utrustning.contains(sokOrd) && sokOrd.matches("[0-9]+"))
                    {
                        model.addElement(map.get(key));
                        skrivitsUt = true;
                    }*/
                    if(utrustning.contains(sokOrd) && !sokOrd.matches("[0-9]+"))
                    {
                        model.addElement(map.get(key));
                        skrivitsUt = true;
                    }
                    else if(map.get(key).matches("[0-9]+") && skrivitsUt == true)
                    {
                        model.addElement(map.get(key));
   
                        String agentFraga = "SELECT NAMN FROM AGENT JOIN INNEHAR_UTRUSTNING ON AGENT.AGENT_ID = INNEHAR_UTRUSTNING.AGENT_ID WHERE INNEHAR_UTRUSTNING.UTRUSTNINGS_ID = " + map.get(key);
                        String agentSvar = DataBaseConnection.getDB().fetchSingle(agentFraga);
                        if(agentSvar == null)
                        {
                            model.addElement("Ej utkvitterad");
                        }
                        else
                        {
                            model.addElement("Utkvitterad av: " + DataBaseConnection.getDB().fetchSingle(agentFraga));
                        }
                    }
                    
                }
                if(skrivitsUt == true)
                {
                String newRow = "-------------------------------------------------";
                model.addElement(newRow);
                }
            }          
        }
        catch(Exception e)
        {
            
        }
        }
    }//GEN-LAST:event_btnSokActionPerformed

    private void btnRegistreraUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraUtrustningActionPerformed
    
    if(Validation.isNotEmpty(txtAdminUtrustningsID) && Validation.isNotEmpty(txtAdminUtrustningsBenamning) && Validation.isHeltal(txtAdminUtrustningsID) && Validation.isNotHelTal(txtAdminUtrustningsBenamning))
    {    
    try{
        
        int nyttID = Integer.parseInt(txtAdminUtrustningsID.getText());
        String benamning = txtAdminUtrustningsBenamning.getText().substring(0,1).toUpperCase();
        String benamning2 = txtAdminUtrustningsBenamning.getText().substring(1);
        String benamning3 = benamning + benamning2;
        String fraga = "INSERT INTO UTRUSTNING VALUES (" + nyttID + ", '" + benamning3 + "')";
        
        InfDB databas = DataBaseConnection.getDB();        
        databas.insert(fraga);
        
        JOptionPane.showMessageDialog(null, "Utrustningen har lagts till!");
        
        
    }
    catch(InfException e)
    {
        JOptionPane.showMessageDialog(null, ("Utrustning med UtrustningsID - " + txtAdminUtrustningsID.getText() + " finns redan!" ));
    }
    listaUtrustning();
    }
   
    }//GEN-LAST:event_btnRegistreraUtrustningActionPerformed

    private void btnRaderaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaUtrustningActionPerformed
        
            if(Validation.isNotSelected(lstAdminUtrustning))   
            {
                if(Validation.startsWithString(lstAdminUtrustning, "----") || Validation.containsWithString(lstAdminUtrustning, "kvittera"))
                {                
                }
                else
                {
                int optionPane = JOptionPane.showConfirmDialog(null, "Vill du radera utrustningen?", "Radera utrustning" , JOptionPane.YES_NO_OPTION);
                if(optionPane == JOptionPane.YES_OPTION)
                {
                try{
                
                    String attTaBort = lstAdminUtrustning.getSelectedValue();
                    String fragan = "";
        
                    if (attTaBort.matches("[0-9]+"))
                    {
                        fragan = "DELETE FROM UTRUSTNING WHERE UTRUSTNINGS_ID = " + attTaBort;
                    }
                    else
                    {
                        fragan = "DELETE FROM UTRUSTNING WHERE BENAMNING = '" + attTaBort + "'";
                    }
        
                    InfDB databas = DataBaseConnection.getDB();
                    databas.delete(fragan);
                    JOptionPane.showMessageDialog(null, "Utrustningen har raderats!");
                    txtAdminUtrustningsBenamning.setText("");
                    txtAdminUtrustningsID.setText("");
                    txtSokUtrustning.setText("");
                
                    String fraga2= "SELECT UTRUSTNINGS_ID, BENAMNING FROM UTRUSTNING";
                    ArrayList<HashMap<String,String>> lista = (DataBaseConnection.getDB().fetchRows(fraga2));
                    DefaultListModel<String> model = new DefaultListModel<>();
                    lstAdminUtrustning.setModel(model);
            
                    for(HashMap<String, String> map: lista)
                    {
                        for(String key : map.keySet())
                        {
                            model.addElement(map.get(key));
                        }
                        String newRow = "-------------------------------------------------";
                        model.addElement(newRow);
                    } 
                    }
    
                catch(InfException e)
                {

                }
                listaUtrustning();
                }
            }
            }    
    }//GEN-LAST:event_btnRaderaUtrustningActionPerformed

    private void btnListaAlla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaAlla1ActionPerformed
        listaUtrustning();
    }//GEN-LAST:event_btnListaAlla1ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        AdminHome obj = new AdminHome();
        obj.setVisible(true);
        obj.setLocationRelativeTo(this);
        obj.setRubrikAgent(Inloggad.getNameInloggad());
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void lstAdminUtrustningValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAdminUtrustningValueChanged

        try{
            String valLista = lstAdminUtrustning.getSelectedValue();
            InfDB databas = DataBaseConnection.getDB();
            txtSokUtrustning.setText("");
            if(valLista != null)
            {

                if (valLista.matches("[0-9]+"))
                {
                    txtTilldelaUtrustningsID.setText(valLista);
                }
                String benamningFraga = "SELECT BENAMNING FROM UTRUSTNING";
                ArrayList<HashMap<String,String>> benamningSvar = DataBaseConnection.getDB().fetchRows(benamningFraga);
                for(HashMap<String,String> key : benamningSvar)
                {
                    for(String enStrang : key.keySet())
                    {
                        key.get(enStrang);
                        if(key.get(enStrang).equals(valLista))
                        {
                            String utrustningsIDFraga = "SELECT UTRUSTNINGS_ID FROM UTRUSTNING WHERE BENAMNING = '" + valLista + "'";
                            String utrustningsIDSvar = databas.fetchSingle(utrustningsIDFraga);
                            txtTilldelaUtrustningsID.setText(utrustningsIDSvar);
                        }
                    }
                }

            }
        }
        catch(InfException e)
        {

        }
    }//GEN-LAST:event_lstAdminUtrustningValueChanged

    private void btnTilldelaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTilldelaUtrustningActionPerformed

        if(Validation.isHeltal(txtTilldelaAgentID) && Validation.isHeltal(txtTilldelaUtrustningsID))
        try
        {
            String fragaUtrustning = "SELECT UTRUSTNINGS_ID FROM UTRUSTNING WHERE UTRUSTNINGS_ID = " + txtTilldelaUtrustningsID.getText();
            String svarUtrustning = DataBaseConnection.getDB().fetchSingle(fragaUtrustning);
            String fragaAgentID = "SELECT AGENT_ID FROM AGENT WHERE AGENT_ID = " + txtTilldelaAgentID.getText() ;
            String svarAgentID = DataBaseConnection.getDB().fetchSingle(fragaAgentID);
            if(svarUtrustning == null)
            {
                JOptionPane.showMessageDialog(null, "Utrustningen finns inte");
            }
            else if(svarAgentID == null)
            {
                JOptionPane.showMessageDialog(null, "Agenten finns inte");
            }
            else
            {
            InfDB databas = DataBaseConnection.getDB();
            String insertFraga = "INSERT INTO INNEHAR_UTRUSTNING VALUES (" + txtTilldelaAgentID.getText() + "," + txtTilldelaUtrustningsID.getText() + ", '2020-01-01')";                 
            databas.insert(insertFraga);
            String agentIDFraga = "SELECT NAMN FROM AGENT WHERE AGENT_ID = " + txtTilldelaAgentID.getText();
            String agentIDSvar = databas.fetchSingle(agentIDFraga);
            JOptionPane.showMessageDialog(null, "Utrustningen har tilldelats " + agentIDSvar +"!");
            }
        }
        catch(InfException e)
        {
            JOptionPane.showMessageDialog(null, "Utrustningen är redan upptagen!");           
        }
        listaUtrustning();
    }//GEN-LAST:event_btnTilldelaUtrustningActionPerformed

    private void btnAterlamnaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAterlamnaUtrustningActionPerformed
        if(Validation.isNotSelected(lstAdminMinUtrustning))
        if(Validation.startsWithString(lstAdminUtrustning, "----") || Validation.containsWithString(lstAdminUtrustning, "kvittera"))
        {                
        }
        else
        try
        {   
            String valLista = lstAdminMinUtrustning.getSelectedValue();
            InfDB databas = DataBaseConnection.getDB();
            if(valLista != null)
            {

                if (valLista.matches("[0-9]+"))
                {
                    String deleteFraga = "DELETE FROM INNEHAR_UTRUSTNING WHERE UTRUSTNINGS_ID = " + valLista;
                    databas.delete(deleteFraga);
                    JOptionPane.showMessageDialog(null, "Utrustningen har återlämnats!");

                }
                String benamningFraga = "SELECT BENAMNING FROM UTRUSTNING";
                ArrayList<HashMap<String,String>> benamningSvar = DataBaseConnection.getDB().fetchRows(benamningFraga);
                for(HashMap<String,String> key : benamningSvar)
                {
                    for(String enStrang : key.keySet())
                    {
                        key.get(enStrang);
                        if(key.get(enStrang).equals(valLista))
                        {
                            String utrustningsIDFraga = "SELECT UTRUSTNINGS_ID FROM UTRUSTNING WHERE BENAMNING = '" + valLista + "'";
                            String utrustningsIDSvar = databas.fetchSingle(utrustningsIDFraga);
                            String deleteFraga = "DELETE FROM INNEHAR_UTRUSTNING WHERE UTRUSTNINGS_ID = " + utrustningsIDSvar;
                            databas.delete(deleteFraga);
                            JOptionPane.showMessageDialog(null, "Utrustningen har återlämnats!");
                            System.out.println(deleteFraga);
                        }

                    }
                }
            }
            
        }
        catch(Exception e)
        {
            
        }
        listaUtrustning();
        listaMinUtrustning();

    }//GEN-LAST:event_btnAterlamnaUtrustningActionPerformed

    private void btnUtkvitteraUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtkvitteraUtrustningActionPerformed
        if(Validation.isNotSelected(lstAdminUtrustning))
        if(Validation.startsWithString(lstAdminUtrustning, "----") || Validation.containsWithString(lstAdminUtrustning, "kvittera"))
        {
        }
        else
        {
        try
        {
            String valLista = lstAdminUtrustning.getSelectedValue();
            InfDB databas = DataBaseConnection.getDB();
            if(valLista != null)
            {

                if (valLista.matches("[0-9]+"))
                {
                    String insertFraga = "INSERT INTO INNEHAR_UTRUSTNING VALUES (" + Inloggad.getIDInloggad() + "," + valLista + ", '2020-01-01')";
                    System.out.println(insertFraga);
                   
                    databas.insert(insertFraga);
                    JOptionPane.showMessageDialog(null, "Utrustningen har utkvitterats!");

                }
                String benamningFraga = "SELECT BENAMNING FROM UTRUSTNING";
                ArrayList<HashMap<String,String>> benamningSvar = DataBaseConnection.getDB().fetchRows(benamningFraga);
                for(HashMap<String,String> key : benamningSvar)
                {
                    for(String enStrang : key.keySet())
                    {
                        key.get(enStrang);
                        if(key.get(enStrang).equals(valLista))
                        {
                            String utrustningsIDFraga = "SELECT UTRUSTNINGS_ID FROM UTRUSTNING WHERE BENAMNING = '" + valLista + "'";
                            String utrustningsIDSvar = databas.fetchSingle(utrustningsIDFraga);
                            System.out.println(utrustningsIDSvar);
                            String insertFraga = "INSERT INTO INNEHAR_UTRUSTNING VALUES (" + Inloggad.getIDInloggad() + "," + utrustningsIDSvar + ", '2020-01-01')";
                            System.out.println(insertFraga);
                            databas.insert(insertFraga);
                            JOptionPane.showMessageDialog(null, "Utrustningen har utkvitterats!");
                        }
                        System.out.println(key.get(enStrang) + " " + valLista);

                    }
                }

            }
        }
        catch(InfException e)
        {
            JOptionPane.showMessageDialog(null, "Utrustningen är redan upptagen!");
        }
        listaMinUtrustning();
        }
    }//GEN-LAST:event_btnUtkvitteraUtrustningActionPerformed

    private void btnListaMinUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaMinUtrustningActionPerformed
        listaMinUtrustning();
    }//GEN-LAST:event_btnListaMinUtrustningActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAterlamnaUtrustning;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListaAlla1;
    private javax.swing.JButton btnListaMinUtrustning;
    private javax.swing.JButton btnRaderaUtrustning;
    private javax.swing.JButton btnRegistreraUtrustning;
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTilldelaUtrustning;
    private javax.swing.JButton btnUtkvitteraUtrustning;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAgentIkon;
    private javax.swing.JLabel lblAgentNamn;
    private javax.swing.JLabel lblBenamning;
    private javax.swing.JLabel lblBenamning1;
    private javax.swing.JLabel lblInstruktioner;
    private javax.swing.JLabel lblInstruktioner1;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblUtrustningsID;
    private javax.swing.JLabel lblUtrustningsID1;
    private javax.swing.JLabel lblValjUtrustning;
    private javax.swing.JList<String> lstAdminMinUtrustning;
    private javax.swing.JList<String> lstAdminUtrustning;
    private javax.swing.JPanel pnlBorderBottom;
    private javax.swing.JPanel pnlBorderTop;
    private javax.swing.JPanel pnlFonster;
    private javax.swing.JScrollPane scpLista;
    private javax.swing.JScrollPane scpMinUtrustning;
    private javax.swing.JTextField txtAdminUtrustningsBenamning;
    private javax.swing.JTextField txtAdminUtrustningsID;
    private javax.swing.JTextField txtSokUtrustning;
    private javax.swing.JTextField txtTilldelaAgentID;
    private javax.swing.JTextField txtTilldelaUtrustningsID;
    // End of variables declaration//GEN-END:variables
}
