/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mib;
import javax.swing.JOptionPane;

/**
 *
 * @author Lukas
 */
public class AgentHome extends javax.swing.JFrame {

    /**
     * Creates new form AgentHome
     */
    public AgentHome() {
        initComponents();
    }
    
    private void setRubrik(String agent)
    {
        lblRubrik.setText("Välkommen " + agent);
    }
    
    public void setAgentNamn(String agent)
    {
        lblAgentNamn.setText(agent);
    }
    
    public void setRubrikAgent(String agent)
    {
        setRubrik(agent);
        setAgentNamn(agent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFonster = new javax.swing.JPanel();
        pnlAliens = new javax.swing.JPanel();
        btnAliens = new javax.swing.JButton();
        pnlOmrade = new javax.swing.JPanel();
        btnOmrade = new javax.swing.JButton();
        pnlUtrustning = new javax.swing.JPanel();
        btnUtrustning = new javax.swing.JButton();
        pnlBytLosenord = new javax.swing.JPanel();
        btnBytLosenord = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        pnlBorderBottom = new javax.swing.JPanel();
        pnlBorderTop = new javax.swing.JPanel();
        lblRubrik = new javax.swing.JLabel();
        lblAgentIkon = new javax.swing.JLabel();
        lblAgentNamn = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        pnlFonster.setBackground(new java.awt.Color(255, 255, 255));
        pnlFonster.setMaximumSize(new java.awt.Dimension(1000, 640));
        pnlFonster.setMinimumSize(new java.awt.Dimension(1000, 640));
        pnlFonster.setName(""); // NOI18N
        pnlFonster.setPreferredSize(new java.awt.Dimension(1000, 640));

        pnlAliens.setBackground(new java.awt.Color(255, 255, 255));
        pnlAliens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlAliens.setMaximumSize(new java.awt.Dimension(200, 175));
        pnlAliens.setMinimumSize(new java.awt.Dimension(200, 175));

        btnAliens.setBackground(new java.awt.Color(255, 255, 255));
        btnAliens.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnAliens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/alien.png"))); // NOI18N
        btnAliens.setText("Aliens");
        btnAliens.setContentAreaFilled(false);
        btnAliens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAliens.setIconTextGap(8);
        btnAliens.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAliens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAliensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAliensLayout = new javax.swing.GroupLayout(pnlAliens);
        pnlAliens.setLayout(pnlAliensLayout);
        pnlAliensLayout.setHorizontalGroup(
            pnlAliensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAliens, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlAliensLayout.setVerticalGroup(
            pnlAliensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAliens, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlOmrade.setBackground(new java.awt.Color(255, 255, 255));
        pnlOmrade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlOmrade.setMaximumSize(new java.awt.Dimension(200, 175));
        pnlOmrade.setMinimumSize(new java.awt.Dimension(200, 175));

        btnOmrade.setBackground(new java.awt.Color(255, 255, 255));
        btnOmrade.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnOmrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/location-pointer.png"))); // NOI18N
        btnOmrade.setText("Område");
        btnOmrade.setContentAreaFilled(false);
        btnOmrade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOmrade.setIconTextGap(8);
        btnOmrade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOmrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOmradeLayout = new javax.swing.GroupLayout(pnlOmrade);
        pnlOmrade.setLayout(pnlOmradeLayout);
        pnlOmradeLayout.setHorizontalGroup(
            pnlOmradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlOmradeLayout.setVerticalGroup(
            pnlOmradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        pnlUtrustning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlUtrustning.setMaximumSize(new java.awt.Dimension(200, 175));
        pnlUtrustning.setMinimumSize(new java.awt.Dimension(200, 175));

        btnUtrustning.setBackground(new java.awt.Color(255, 255, 255));
        btnUtrustning.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnUtrustning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/binoculars.png"))); // NOI18N
        btnUtrustning.setText("Utrustning");
        btnUtrustning.setContentAreaFilled(false);
        btnUtrustning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUtrustning.setIconTextGap(8);
        btnUtrustning.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtrustningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUtrustningLayout = new javax.swing.GroupLayout(pnlUtrustning);
        pnlUtrustning.setLayout(pnlUtrustningLayout);
        pnlUtrustningLayout.setHorizontalGroup(
            pnlUtrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlUtrustningLayout.setVerticalGroup(
            pnlUtrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlBytLosenord.setBackground(new java.awt.Color(255, 255, 255));
        pnlBytLosenord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlBytLosenord.setMaximumSize(new java.awt.Dimension(200, 175));
        pnlBytLosenord.setMinimumSize(new java.awt.Dimension(200, 175));

        btnBytLosenord.setBackground(new java.awt.Color(255, 255, 255));
        btnBytLosenord.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnBytLosenord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/password(2).png"))); // NOI18N
        btnBytLosenord.setText("Byt lösenord");
        btnBytLosenord.setContentAreaFilled(false);
        btnBytLosenord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBytLosenord.setIconTextGap(8);
        btnBytLosenord.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBytLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytLosenordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBytLosenordLayout = new javax.swing.GroupLayout(pnlBytLosenord);
        pnlBytLosenord.setLayout(pnlBytLosenordLayout);
        pnlBytLosenordLayout.setHorizontalGroup(
            pnlBytLosenordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBytLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlBytLosenordLayout.setVerticalGroup(
            pnlBytLosenordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBytLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnLoggaUt.setBackground(new java.awt.Color(255, 255, 255));
        btnLoggaUt.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLoggaUt.setContentAreaFilled(false);
        btnLoggaUt.setMaximumSize(new java.awt.Dimension(75, 30));
        btnLoggaUt.setMinimumSize(new java.awt.Dimension(75, 30));
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        pnlBorderBottom.setBackground(new java.awt.Color(220, 220, 220));
        pnlBorderBottom.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlBorderBottom.setMaximumSize(new java.awt.Dimension(1000, 40));
        pnlBorderBottom.setMinimumSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout pnlBorderBottomLayout = new javax.swing.GroupLayout(pnlBorderBottom);
        pnlBorderBottom.setLayout(pnlBorderBottomLayout);
        pnlBorderBottomLayout.setHorizontalGroup(
            pnlBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBorderBottomLayout.setVerticalGroup(
            pnlBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        pnlBorderTop.setBackground(new java.awt.Color(220, 220, 220));
        pnlBorderTop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlBorderTop.setMaximumSize(new java.awt.Dimension(1000, 80));
        pnlBorderTop.setMinimumSize(new java.awt.Dimension(1000, 80));
        pnlBorderTop.setPreferredSize(new java.awt.Dimension(1000, 80));

        lblRubrik.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblRubrik.setText("Välkommen Agent K!");

        lblAgentIkon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/spy.png"))); // NOI18N

        lblAgentNamn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblAgentNamn.setText("Agent K");

        btnHome.setBackground(new java.awt.Color(220, 220, 220));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBorderTopLayout = new javax.swing.GroupLayout(pnlBorderTop);
        pnlBorderTop.setLayout(pnlBorderTopLayout);
        pnlBorderTopLayout.setHorizontalGroup(
            pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242)
                .addComponent(lblAgentIkon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAgentNamn)
                .addGap(15, 15, 15))
        );
        pnlBorderTopLayout.setVerticalGroup(
            pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBorderTopLayout.createSequentialGroup()
                        .addGroup(pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlBorderTopLayout.createSequentialGroup()
                                .addComponent(lblAgentNamn)
                                .addGap(14, 14, 14))
                            .addGroup(pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAgentIkon)))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorderTopLayout.createSequentialGroup()
                        .addComponent(lblRubrik)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout pnlFonsterLayout = new javax.swing.GroupLayout(pnlFonster);
        pnlFonster.setLayout(pnlFonsterLayout);
        pnlFonsterLayout.setHorizontalGroup(
            pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFonsterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAliens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUtrustning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBytLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(276, 276, 276))
            .addGroup(pnlFonsterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFonsterLayout.createSequentialGroup()
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBorderTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFonsterLayout.setVerticalGroup(
            pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFonsterLayout.createSequentialGroup()
                .addComponent(pnlBorderTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAliens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBytLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFonster, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBytLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLosenordActionPerformed
        BytaLosenord byta = new BytaLosenord();
        byta.setVisible(true);
        byta.setLocationRelativeTo(this);// TODO add your handling code here:
    }//GEN-LAST:event_btnBytLosenordActionPerformed

    private void btnAliensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAliensActionPerformed
        AgentAliens obj = new AgentAliens();
        obj.setVisible(true);
        obj.setLocationRelativeTo(this);
        obj.setAgentNamn(Inloggad.getNameInloggad());
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnAliensActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
                int optionPane = JOptionPane.showConfirmDialog(null, "Vill du logga ut?", "Logga ut" , JOptionPane.YES_NO_OPTION);
        if(optionPane == JOptionPane.YES_OPTION)
        {
            mib.Start.main(null);
            this.dispose();
        }
        else
        {     
        }
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmradeActionPerformed
        AgentOmrade obj = new AgentOmrade();
        obj.setVisible(true);
        obj.setLocationRelativeTo(this);
        obj.setAgentNamn(Inloggad.getNameInloggad());
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnOmradeActionPerformed

    private void btnUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtrustningActionPerformed
        AgentUtrustning obj = new AgentUtrustning();
        obj.setVisible(true);
        obj.setLocationRelativeTo(this);
        obj.setAgentNamn(Inloggad.getNameInloggad());
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnUtrustningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAliens;
    private javax.swing.JButton btnBytLosenord;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnOmrade;
    private javax.swing.JButton btnUtrustning;
    private javax.swing.JLabel lblAgentIkon;
    private javax.swing.JLabel lblAgentNamn;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JPanel pnlAliens;
    private javax.swing.JPanel pnlBorderBottom;
    private javax.swing.JPanel pnlBorderTop;
    private javax.swing.JPanel pnlBytLosenord;
    private javax.swing.JPanel pnlFonster;
    private javax.swing.JPanel pnlOmrade;
    private javax.swing.JPanel pnlUtrustning;
    // End of variables declaration//GEN-END:variables
}
