/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;
import javax.swing.JOptionPane;
import oru.inf.*;

import javax.swing.JOptionPane;

/**
 *
 * @author jonte
 */
public class AlienHome extends javax.swing.JFrame {

    /**
     * Creates new form AlienMainpage
     */
    public AlienHome() {
        initComponents();
    }
    
    private void setRubrik(String alien)
    {
        lblWcome.setText("Välkommen " + alien);
    }
    
    public void setAlienNamn(String alien)
    {
        lblAlienNamn.setText(alien);
    }
    
    public void setRubrikAlien(String alien)
    {
        setRubrik(alien);
        setAlienNamn(alien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBakgrund = new javax.swing.JPanel();
        pnlTopBorder = new javax.swing.JPanel();
        lblHembild = new javax.swing.JLabel();
        lblAlienNamn = new javax.swing.JLabel();
        lblAlienBild = new javax.swing.JLabel();
        lblWcome = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        btnBytaLosenord = new javax.swing.JButton();
        btnOmrade = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        lblBesoksstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        pnlBakgrund.setBackground(new java.awt.Color(255, 255, 255));
        pnlBakgrund.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlBakgrund.setPreferredSize(new java.awt.Dimension(1000, 600));

        pnlTopBorder.setBackground(new java.awt.Color(220, 220, 220));
        pnlTopBorder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlTopBorder.setMaximumSize(new java.awt.Dimension(1000, 80));
        pnlTopBorder.setMinimumSize(new java.awt.Dimension(1000, 80));
        pnlTopBorder.setPreferredSize(new java.awt.Dimension(1000, 80));

        lblHembild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/home.png"))); // NOI18N

        lblAlienNamn.setText("AlienNamn");

        lblAlienBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/alien.png"))); // NOI18N
        lblAlienBild.setMaximumSize(new java.awt.Dimension(60, 60));
        lblAlienBild.setMinimumSize(new java.awt.Dimension(60, 60));

        lblWcome.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblWcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWcome.setText("Välkommen AlienNamn!");

        javax.swing.GroupLayout pnlTopBorderLayout = new javax.swing.GroupLayout(pnlTopBorder);
        pnlTopBorder.setLayout(pnlTopBorderLayout);
        pnlTopBorderLayout.setHorizontalGroup(
            pnlTopBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHembild, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(lblWcome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(lblAlienBild, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlienNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTopBorderLayout.setVerticalGroup(
            pnlTopBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHembild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTopBorderLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pnlTopBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlienBild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopBorderLayout.createSequentialGroup()
                        .addComponent(lblAlienNamn)
                        .addGap(19, 19, 19)))
                .addContainerGap())
            .addComponent(lblWcome, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        pnlBottom.setBackground(new java.awt.Color(220, 220, 220));
        pnlBottom.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlBottom.setMaximumSize(new java.awt.Dimension(1000, 40));
        pnlBottom.setMinimumSize(new java.awt.Dimension(1000, 40));
        pnlBottom.setPreferredSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        btnBytaLosenord.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnBytaLosenord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/password(2).png"))); // NOI18N
        btnBytaLosenord.setText("Byt lösenord");
        btnBytaLosenord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnBytaLosenord.setContentAreaFilled(false);
        btnBytaLosenord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBytaLosenord.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBytaLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytaLosenordActionPerformed(evt);
            }
        });

        btnOmrade.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnOmrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/location-pointer.png"))); // NOI18N
        btnOmrade.setText("Område");
        btnOmrade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnOmrade.setContentAreaFilled(false);
        btnOmrade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOmrade.setInheritsPopupMenu(true);
        btnOmrade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOmrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmradeActionPerformed(evt);
            }
        });

        btnLoggaUt.setBackground(new java.awt.Color(255, 255, 255));
        btnLoggaUt.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLoggaUt.setContentAreaFilled(false);
        btnLoggaUt.setMaximumSize(new java.awt.Dimension(75, 30));
        btnLoggaUt.setMinimumSize(new java.awt.Dimension(75, 30));
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBakgrundLayout = new javax.swing.GroupLayout(pnlBakgrund);
        pnlBakgrund.setLayout(pnlBakgrundLayout);
        pnlBakgrundLayout.setHorizontalGroup(
            pnlBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBakgrundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBesoksstatus)
                .addGap(579, 579, 579))
            .addGroup(pnlBakgrundLayout.createSequentialGroup()
                .addGroup(pnlBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBakgrundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBakgrundLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnBytaLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBakgrundLayout.setVerticalGroup(
            pnlBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBakgrundLayout.createSequentialGroup()
                .addComponent(pnlTopBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblBesoksstatus)
                .addGap(52, 52, 52)
                .addGroup(pnlBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBytaLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBakgrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBakgrund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBytaLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytaLosenordActionPerformed
        BytaLosenord byta = new BytaLosenord();
        byta.setVisible(true);
        byta.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnBytaLosenordActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        int optionPane = JOptionPane.showConfirmDialog(null, "Vill du logga ut?", "Logga ut" , JOptionPane.YES_NO_OPTION);
        if(optionPane == JOptionPane.YES_OPTION)
        {
            mib.Start.main(null);
            this.dispose();
        }
        else
        {     
        }     
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmradeActionPerformed
        AlienOmrade obj = new AlienOmrade();
        obj.setVisible(true);
        obj.setLocationRelativeTo(this);
        obj.setAlienNamn(Inloggad.getNameInloggad());
        this.dispose();
    }//GEN-LAST:event_btnOmradeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytaLosenord;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnOmrade;
    private javax.swing.JLabel lblAlienBild;
    private javax.swing.JLabel lblAlienNamn;
    private javax.swing.JLabel lblBesoksstatus;
    private javax.swing.JLabel lblHembild;
    private javax.swing.JLabel lblWcome;
    private javax.swing.JPanel pnlBakgrund;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTopBorder;
    // End of variables declaration//GEN-END:variables
}
