package mib;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Lukas Brolin, Daniel Antonsson  Jonatan Angergård
 */
public class BytaLosenord extends javax.swing.JFrame {
    /**
     * Creates new form BytaLosenord
     */
    public BytaLosenord()
    {
        initComponents();
        checkUserName();    
    }
    
    // Sätter det inloggade IDt som användarnamn vilket även är non-editable 
    private void checkUserName()
    {
        txtAnvandarnamn.setText(Inloggad.getIDInloggad());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFonster = new javax.swing.JPanel();
        lblRubrik = new javax.swing.JLabel();
        lblAnvandarnamn = new javax.swing.JLabel();
        lblLosenordNu = new javax.swing.JLabel();
        lblLosenordNytt = new javax.swing.JLabel();
        lblLosenordUpprepa = new javax.swing.JLabel();
        txtAnvandarnamn = new javax.swing.JTextField();
        pswLosenordNu = new javax.swing.JPasswordField();
        pswLosenordNy = new javax.swing.JPasswordField();
        pswLosenordUpprepa = new javax.swing.JPasswordField();
        btnAndraLosenord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));

        pnlFonster.setBackground(new java.awt.Color(255, 255, 255));
        pnlFonster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlFonster.setMaximumSize(new java.awt.Dimension(700, 500));
        pnlFonster.setMinimumSize(new java.awt.Dimension(600, 400));
        pnlFonster.setPreferredSize(new java.awt.Dimension(646, 446));

        lblRubrik.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblRubrik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRubrik.setText("Byt Lösenord");

        lblAnvandarnamn.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblAnvandarnamn.setText("Användarnamn:");

        lblLosenordNu.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblLosenordNu.setText("Nuvarande lösenord:");

        lblLosenordNytt.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblLosenordNytt.setText("Nytt lösenord:");

        lblLosenordUpprepa.setFont(new java.awt.Font("Open Sans Semibold", 0, 14)); // NOI18N
        lblLosenordUpprepa.setText("Upprepa nytt lösenord:");

        txtAnvandarnamn.setEditable(false);
        txtAnvandarnamn.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtAnvandarnamn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pswLosenordNu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pswLosenordNy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pswLosenordUpprepa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pswLosenordUpprepa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswLosenordUpprepaKeyPressed(evt);
            }
        });

        btnAndraLosenord.setBackground(new java.awt.Color(255, 255, 255));
        btnAndraLosenord.setFont(new java.awt.Font("Open Sans Semibold", 0, 12)); // NOI18N
        btnAndraLosenord.setText("Ändra");
        btnAndraLosenord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAndraLosenord.setContentAreaFilled(false);
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFonsterLayout = new javax.swing.GroupLayout(pnlFonster);
        pnlFonster.setLayout(pnlFonsterLayout);
        pnlFonsterLayout.setHorizontalGroup(
            pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFonsterLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFonsterLayout.createSequentialGroup()
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFonsterLayout.createSequentialGroup()
                        .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAndraLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFonsterLayout.createSequentialGroup()
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLosenordNytt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLosenordNu, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLosenordUpprepa, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAnvandarnamn, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAnvandarnamn)
                                    .addComponent(pswLosenordNu)
                                    .addComponent(pswLosenordNy)
                                    .addComponent(pswLosenordUpprepa, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                        .addGap(190, 190, 190))))
        );
        pnlFonsterLayout.setVerticalGroup(
            pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFonsterLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnvandarnamn)
                    .addComponent(txtAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenordNu)
                    .addComponent(pswLosenordNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenordNytt)
                    .addComponent(pswLosenordNy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFonsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenordUpprepa)
                    .addComponent(pswLosenordUpprepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAndraLosenord)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFonster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlFonster, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
        if(Validation.isNotEmpty(txtAnvandarnamn) && Validation.isNotEmpty(pswLosenordNu) && Validation.isNotEmpty(pswLosenordNy) && Validation.isNotEmpty(pswLosenordUpprepa) && Validation.passwordCheck(pswLosenordNy) && Validation.passwordCheck(pswLosenordUpprepa) )
        {    
            try
            {
                String id = txtAnvandarnamn.getText();
                String questionPassword = "select LOSENORD from " + Inloggad.getTypeInloggad() + " where " + Inloggad.getTypeInloggad() + "_ID =" + id;
                String svarPassword = DataBaseConnection.getDB().fetchSingle(questionPassword);
                String questionUsername = "select " + Inloggad.getTypeInloggad() + "_ID from " + Inloggad.getTypeInloggad() + " where " + Inloggad.getTypeInloggad() + "_ID =" + id;
                String svarUsername = DataBaseConnection.getDB().fetchSingle(questionUsername);
            
                if(!id.equals(svarUsername) || !pswLosenordNu.getText().equals(svarPassword))
                {
                    JOptionPane.showMessageDialog(null, "Ditt lösenord är felaktigt");
                }
                else if(!pswLosenordNy.getText().equals(pswLosenordUpprepa.getText()))
                {
                    JOptionPane.showMessageDialog(null, "Lösenorden överrensstämmer inte");
                }
                else
                {
                    String question = "update " + Inloggad.getTypeInloggad() + " set LOSENORD ='" +  pswLosenordNy.getText() + "' where " + Inloggad.getTypeInloggad() + "_ID=" + id;         
                    String svar = DataBaseConnection.getDB().fetchSingle(question);
                    JOptionPane.showMessageDialog(null, "Ditt lösenord har ändrats!");
                    this.dispose();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Vänligen fyll i alla rutor");
        }  
    }//GEN-LAST:event_btnAndraLosenordActionPerformed
    
    
    //    Klickar på knappen btnAndraLosenord vid Enter-tryck.
    private void pswLosenordUpprepaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswLosenordUpprepaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnAndraLosenord.doClick();
        }
    }//GEN-LAST:event_pswLosenordUpprepaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JLabel lblAnvandarnamn;
    private javax.swing.JLabel lblLosenordNu;
    private javax.swing.JLabel lblLosenordNytt;
    private javax.swing.JLabel lblLosenordUpprepa;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JPanel pnlFonster;
    private javax.swing.JPasswordField pswLosenordNu;
    private javax.swing.JPasswordField pswLosenordNy;
    private javax.swing.JPasswordField pswLosenordUpprepa;
    private javax.swing.JTextField txtAnvandarnamn;
    // End of variables declaration//GEN-END:variables
}
