

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
*   En Inloggning-ruta som ger alternativ till att logga in till antingen Alien, Agent eller Admin-agent
*/

/**
 *
 * @author Lukas Brolin, Daniel Antonsson & Jonatan Angergård
 */
package mib;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import oru.inf.*;

public class Inloggning extends javax.swing.JFrame {

    public Inloggning(InfDB idb)
    {
        initComponents();
        this.setLocationRelativeTo(null); //Placerar den initierade rutan i mitten av skärmen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        pnlBackground = new javax.swing.JPanel();
        pnlBorderTop = new javax.swing.JPanel();
        lblAgentLogin1 = new javax.swing.JLabel();
        pnlAgent = new javax.swing.JPanel();
        lblAgentLogin = new javax.swing.JLabel();
        lblAgentUser = new javax.swing.JLabel();
        lblAgentPassword = new javax.swing.JLabel();
        btnAgentLogin = new javax.swing.JButton();
        lblAgentIcon = new javax.swing.JLabel();
        txtAgentUser = new javax.swing.JTextField();
        pswAgent = new javax.swing.JPasswordField();
        pnlAlienLogin = new javax.swing.JPanel();
        lblAlienLogin = new javax.swing.JLabel();
        lblAlienUser = new javax.swing.JLabel();
        lblAlienPassword = new javax.swing.JLabel();
        btnAlienLogin = new javax.swing.JButton();
        lblAlienIcon = new javax.swing.JLabel();
        txtAlienUser = new javax.swing.JTextField();
        pswAlien = new javax.swing.JPasswordField();
        pnlBorderBottom = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setSize(new java.awt.Dimension(1000, 640));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMaximumSize(new java.awt.Dimension(1000, 600));
        pnlBackground.setMinimumSize(new java.awt.Dimension(1000, 600));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1000, 600));

        pnlBorderTop.setBackground(new java.awt.Color(220, 220, 220));
        pnlBorderTop.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pnlBorderTop.setMaximumSize(new java.awt.Dimension(1000, 80));
        pnlBorderTop.setMinimumSize(new java.awt.Dimension(1000, 80));
        pnlBorderTop.setPreferredSize(new java.awt.Dimension(1000, 80));

        lblAgentLogin1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblAgentLogin1.setForeground(new java.awt.Color(0, 0, 0));
        lblAgentLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgentLogin1.setText("Välkommen till MIB Nordiska Sektorn");
        lblAgentLogin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBorderTopLayout = new javax.swing.GroupLayout(pnlBorderTop);
        pnlBorderTop.setLayout(pnlBorderTopLayout);
        pnlBorderTopLayout.setHorizontalGroup(
            pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderTopLayout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(lblAgentLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        pnlBorderTopLayout.setVerticalGroup(
            pnlBorderTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorderTopLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblAgentLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlAgent.setBackground(new java.awt.Color(255, 255, 255));
        pnlAgent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlAgent.setPreferredSize(new java.awt.Dimension(250, 350));

        lblAgentLogin.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblAgentLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgentLogin.setText("Logga in som Agent");
        lblAgentLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAgentUser.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblAgentUser.setText("Användarnamn:");

        lblAgentPassword.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblAgentPassword.setText("Lösenord:");

        btnAgentLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnAgentLogin.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnAgentLogin.setText("Logga in");
        btnAgentLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAgentLogin.setContentAreaFilled(false);
        btnAgentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentLoginActionPerformed(evt);
            }
        });

        lblAgentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/spy.png"))); // NOI18N

        txtAgentUser.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtAgentUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAgentUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentUserActionPerformed(evt);
            }
        });

        pswAgent.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        pswAgent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pswAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswAgentActionPerformed(evt);
            }
        });
        pswAgent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswAgentKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgentLayout = new javax.swing.GroupLayout(pnlAgent);
        pnlAgent.setLayout(pnlAgentLayout);
        pnlAgentLayout.setHorizontalGroup(
            pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgentLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblAgentIcon)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgentLayout.createSequentialGroup()
                .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgentLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentUser)
                            .addComponent(lblAgentPassword))
                        .addGap(35, 35, 35)
                        .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgentUser)
                            .addComponent(pswAgent)))
                    .addGroup(pnlAgentLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgentLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(lblAgentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        pnlAgentLayout.setVerticalGroup(
            pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAgentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblAgentIcon)
                .addGap(38, 38, 38)
                .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentUser)
                    .addComponent(txtAgentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentPassword)
                    .addComponent(pswAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnAgentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pnlAlienLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlAlienLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlAlienLogin.setPreferredSize(new java.awt.Dimension(250, 350));

        lblAlienLogin.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblAlienLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlienLogin.setText("Logga in som Alien");
        lblAlienLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAlienUser.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblAlienUser.setText("Användarnamn:");

        lblAlienPassword.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblAlienPassword.setText("Lösenord:");

        btnAlienLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnAlienLogin.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnAlienLogin.setText("Logga in");
        btnAlienLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAlienLogin.setContentAreaFilled(false);
        btnAlienLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlienLoginActionPerformed(evt);
            }
        });

        lblAlienIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mib/alien.png"))); // NOI18N

        txtAlienUser.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        txtAlienUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAlienUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlienUserActionPerformed(evt);
            }
        });

        pswAlien.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        pswAlien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pswAlien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswAlienKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlAlienLoginLayout = new javax.swing.GroupLayout(pnlAlienLogin);
        pnlAlienLogin.setLayout(pnlAlienLoginLayout);
        pnlAlienLoginLayout.setHorizontalGroup(
            pnlAlienLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlienLoginLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblAlienIcon)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlienLoginLayout.createSequentialGroup()
                .addGroup(pnlAlienLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAlienLoginLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlAlienLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlienUser)
                            .addComponent(lblAlienPassword))
                        .addGap(35, 35, 35)
                        .addGroup(pnlAlienLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlienUser)
                            .addComponent(pswAlien)))
                    .addGroup(pnlAlienLoginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlienLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlienLoginLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(lblAlienLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        pnlAlienLoginLayout.setVerticalGroup(
            pnlAlienLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlienLoginLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAlienLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblAlienIcon)
                .addGap(38, 38, 38)
                .addGroup(pnlAlienLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlienUser)
                    .addComponent(txtAlienUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlAlienLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlienPassword)
                    .addComponent(pswAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnAlienLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pnlBorderBottom.setBackground(new java.awt.Color(220, 220, 220));
        pnlBorderBottom.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlBorderBottom.setMaximumSize(new java.awt.Dimension(1000, 40));
        pnlBorderBottom.setMinimumSize(new java.awt.Dimension(1000, 40));
        pnlBorderBottom.setPreferredSize(new java.awt.Dimension(1000, 40));

        javax.swing.GroupLayout pnlBorderBottomLayout = new javax.swing.GroupLayout(pnlBorderBottom);
        pnlBorderBottom.setLayout(pnlBorderBottomLayout);
        pnlBorderBottomLayout.setHorizontalGroup(
            pnlBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlBorderBottomLayout.setVerticalGroup(
            pnlBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pnlAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(pnlAlienLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBorderTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlBorderTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAlienLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(pnlBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentLoginActionPerformed
        if(Validation.isNotEmpty(txtAgentUser) && Validation.isNotEmpty(pswAgent))
        {
            try
            {
                String id = txtAgentUser.getText();
                String question = "Select LOSENORD from AGENT where AGENT_ID=" + id;
                String svar = DataBaseConnection.getDB().fetchSingle(question);
               
                if(pswAgent.getText().equals(svar)) 
                {
                    //Letar efter namn och administrator från agent med det angivna idt
                    String questionName = "Select NAMN from AGENT where Agent_ID=" + id;
                    String svarName = DataBaseConnection.getDB().fetchSingle(questionName);
                    String question2 = "Select ADMINISTRATOR from AGENT where Agent_ID=" + id;
                    String svar2 = DataBaseConnection.getDB().fetchSingle(question2);
                    if(svar2.equals("N"))
                    {
                        //Ändrar sidan till AgentHome, sätter fönstret på samma plats som Inloggning och ändrar Rubrik och AgentNamn i AgentHome till det anvigna IDt's namn
                        AgentHome agentPage = new AgentHome(); //Skapar nytt objekt av AgentHome
                        agentPage.setVisible(true);
                        agentPage.setLocationRelativeTo(this);//Vid knapptryck på Logga In så visar programmet AgentHome, Kommer behöva göra vilkor osv.
                        Inloggad nyInlogg = new Inloggad("Agent", txtAgentUser.getText(), svarName);
                        agentPage.setRubrikAgent(Inloggad.getNameInloggad());
                        this.dispose();
                    }
                    else
                    {
                        //Ã„ndrar sidan till AdminHome, sÃ¤tter fÃ¶nstret pÃ¥ samma plats som Inloggning och Ã¤ndrar Rubrik och AgentNamn i AdminHome till det anvigna IDt's namn
                        AdminHome adminPage = new AdminHome();
                        adminPage.setVisible(true);
                        adminPage.setLocationRelativeTo(this);
                        Inloggad nyInlogg = new Inloggad("Agent", txtAgentUser.getText(), svarName);
                        adminPage.setRubrikAgent(Inloggad.getNameInloggad());
                        this.dispose();
                    }
                }   
                else
                {
                    JOptionPane.showMessageDialog(null, "Fel lösenord");
                }
            } 
            catch(Exception e) // MÃ…STE JUSTERAS
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnAgentLoginActionPerformed

    private void txtAgentUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgentUserActionPerformed

    private void btnAlienLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlienLoginActionPerformed
        // TODO add your handling code here:
           if(Validation.isNotEmpty(txtAlienUser) && Validation.isNotEmpty(pswAlien))
        {
            try
            {
                String id = txtAlienUser.getText();
                String question = "Select LOSENORD from ALIEN where ALIEN_ID=" + id;
                String svar = DataBaseConnection.getDB().fetchSingle(question);
                String questionName = "Select NAMN from ALIEN where ALIEN_ID=" + id;
                String svarName = DataBaseConnection.getDB().fetchSingle(questionName);
                
                if(pswAlien.getText().equals(svar)) 
                {
                    AlienHome alienPage = new AlienHome(); //Skapar nytt objekt av AgentHome
                    alienPage.setVisible(true); //Vid knapptryck pÃ¥ Logga In sÃ¥ visar programmet AgentHome, Kommer behÃ¶va gÃ¶ra vilkor osv.
                    alienPage.setLocationRelativeTo(this);
                    Inloggad nyInlogg = new Inloggad("Alien", txtAlienUser.getText(), svarName);
                    alienPage.setRubrikAlien(nyInlogg.getNameInloggad());
                    this.dispose();    
                }
                    
                else
                {
                    JOptionPane.showMessageDialog(null, "Fel lösenord");
                }
            } 
            catch(Exception e) // MÃ…STE JUSTERAS
            {
            }
        }
    }//GEN-LAST:event_btnAlienLoginActionPerformed

    private void txtAlienUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlienUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlienUserActionPerformed

    private void pswAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswAgentActionPerformed
    
    //Tillåter Enter-klick för att komma vidare
    private void pswAgentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswAgentKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnAgentLogin.doClick();
        }

    }//GEN-LAST:event_pswAgentKeyPressed

    //Tillåter Enter-klick för att komma vidare
    private void pswAlienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswAlienKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnAlienLogin.doClick();
        }
    }//GEN-LAST:event_pswAlienKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgentLogin;
    private javax.swing.JButton btnAlienLogin;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel lblAgentIcon;
    private javax.swing.JLabel lblAgentLogin;
    private javax.swing.JLabel lblAgentLogin1;
    private javax.swing.JLabel lblAgentPassword;
    private javax.swing.JLabel lblAgentUser;
    private javax.swing.JLabel lblAlienIcon;
    private javax.swing.JLabel lblAlienLogin;
    private javax.swing.JLabel lblAlienPassword;
    private javax.swing.JLabel lblAlienUser;
    private javax.swing.JPanel pnlAgent;
    private javax.swing.JPanel pnlAlienLogin;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBorderBottom;
    private javax.swing.JPanel pnlBorderTop;
    private javax.swing.JPasswordField pswAgent;
    private javax.swing.JPasswordField pswAlien;
    private javax.swing.JTextField txtAgentUser;
    private javax.swing.JTextField txtAlienUser;
    // End of variables declaration//GEN-END:variables
}
